### ISSUE TITLE
[Shaman] Totem of Ancestral Guidance not working

### ISSUE THREAD

**Issue by Bludkraze** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3246]
I have tested it today after some rumor that the +85 spelldmg are not applied to Lightning Bolt and Chain Lightning.

I made my char completely naked and casted LB rank 2 a while without the totem equiped and then a while with it equipped -> a stable 29-33 non crit hit consistent.

Now i did the same for LB rank 12 and get a stable 620 avg and max hit 683 in both situations. 

Under this circumstances I can safely assume the Relic isnt working at all. Not sure for the rare Version, but will test it ASAP.

**Comment by Kvout** [comment]
This totem still not working...Pls guys fix it,how hard can be to fix one item?

**Comment by Kvout** [comment]
Bump

**Comment by scootypuff** [comment]
https://vid.me/stVC adding my video contribution to the issue

**Comment by scootypuff** [comment]
No update, is there anything I can do to help fix this issue?

**Comment by noppiz** [comment]
bump

**Comment by scootypuff** [comment]
I wish

**Comment by devidao** [comment]
Fixed, coming soon on PTR

**Comment by Bludkraze** [comment]
Lol i left this Server 2 yrs ago and such a simple thing not fixed... This is amazing

**Comment by Testedx** [comment]
Confirmed 6/9/16 Working tested w. Kildrazien and Kornn of  <The Peoples Champion> we can both confirm it is working. We first tested Rank 1 lightingbolt w. the blue verison. Then we tested no totem at all w. Rank 1 lightingbolt Clear the effect of that was working. So we went on to test the epic version i obtained tonight Looking at the numbers we came to the quick conclusion in a matter of 2 casts it was working correctly.
