### ISSUE TITLE
[Dungeon][Mount Hyjal][Azgalor] Dying before doom debuff runs out avoids spawn of doomguards

### ISSUE THREAD

**Issue by Arastrus** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3399]
What issue name says.

Expected behaviour: Player with the doom debuff spawn a doomguard on their position, regardless if they die before the debuff runs out or not.
Observed behaviour: Player with the doom debuff dying before it runs out avoids the sapwn of the doomguard.

Kind regards,
Shariva

**Comment by devidao** [comment]
Fixed, coming soon on PTR

**Comment by Arastrus** [comment]
Still an issue. Target Alt-F4ing causes no infernal as well!
