### ISSUE TITLE
[Quest][Terokkar Forest]Stymying the Arakkoa

### ISSUE THREAD

**Issue by Ohaio** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3637]
Quest [Stymying the Arakkoa](http://www.wow-one.com/database/?quest=9987) is not completable due to the Mob [Ayit](http://www.wow-one.com/database/?npc=18540) not being spawned. 

Should spawn at location 59.4, 23,5 - inside the house there.

**Comment by beaten** [comment]
Ayit is still not spawning.  Trying to complete quests/chains.  Hopefully this gets fixed soon!

**Comment by devastator** [comment]
Fixed. Soon on PTR

**Comment by devidao** [comment]
Fixed

**Comment by jdizzle13** [comment]
Ayit still not spawning, been waiting 20 minutes outside of the hut.

**Comment by devastator** [comment]
Fix applied to Live with patch 14.22
