### ISSUE TITLE
Bitter Rivals

### ISSUE THREAD

**Issue by Paraffine** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3823]
In this quest you're supposed to interact with a "Guarded Thunder Ale Barrel", then you should be able to speak with Jarven Thunderbrew in order tomake him go upstair and interact again with the barrel to "compromise" it, but the quest bugs after the first interaction with the barrel because you can't speak with Jarven (you should "turn in" the quest to him and receive the next step if I recall correctly).

**Comment by lajhar** [comment]
Issue confirmed.

**How it is working on the server:**
When you turn in the first [quest (403)](www.wowhead.com/quest=403/guarded-thunderbrew-barrel), the [NPC (1373) ](http://www.wowhead.com/npc=1373)in front of the quest object does not give the following [quest (308)](http://www.wowhead.com/quest=308/distracting-jarven).

**How it is should work:**
After turning in the first [quest (403)](www.wowhead.com/quest=403/guarded-thunderbrew-barrel), the [NPC (1373) ](http://www.wowhead.com/npc=1373)in front of the quest object should give the following [quest (308)](http://www.wowhead.com/quest=308/distracting-jarven). In this quest, the player should distract him (he is the guard of the barrel) by buying him a [Thunder Ale](http://www.wowhead.com/item=2686). When he got distracted, the player should be able to switch the barrels, and complete the quest.

**Reproduction guide:**

- Create any character in alliance
- .gm off
- .gm visible on
- .quest add 310
- .go creature Jarven_Thunderbrew
- Interact with the barrel behind him, and turn in [quest (403)](www.wowhead.com/quest=403/guarded-thunderbrew-barrel)
- Observe that [Jarven Thunderbrew](http://www.wowhead.com/npc=1373/jarven-thunderbrew) does not give the following [quest (308)](http://www.wowhead.com/quest=308/distracting-jarven)

**Comment by devidao** [comment]
Fixed, coming soon on PTR.

**Comment by lajhar** [comment]
Fix denied on PTR.
Jarven Thunderbrew still does not give the quest no. 308, after turning in quest no 310 to the barrel behind him.
