### ISSUE TITLE
[NPC] [Terokkar Forest] Empoor

### ISSUE THREAD

**Issue by gupostalgu** [FeenixServerProject/Archangel_2.4.3_Bugtracker#728]
<a href="http://old.wowhead.com/npc=18482">Empoor</a> and his <a href="http://old.wowhead.com/npc=18483">bodyguard</a> supposed to be walking by the road from fork near Shattrath to Tuurem. But our one is standing still near the fork.
Also, for finishing <a href="http://old.wowhead.com/quest=9978">By Any Means Necessary</a> quest U have to beat him mostly to death, for yellow question mark above his head to appear.

**Comment by devastator** [comment]
Fixed. Soon on PTR

**Comment by lajhar** [comment]
Fix Denied on PTR. The script is still not working, turning in the quest is available without fighting against him.
